### ISSUE TITLE
Getting stuck at 29%

### ISSUE THREAD

**Issue by Moebytes** [FedericoCarboni/eloquent-ffmpeg#17]
I am using this to download animated shows, and it seems like on the latest version `v0.14.0` all of the downloads are [getting stuck at 29%.](https://github.com/Tenpi/Crunchyroll-Downloader/issues/7) It does however work perfectly fine on `v0.13.0-alpha.0`. I haven't really changed anything on my end apart from updating the package, so I think the issue originates from here. For reference, all of my code can be found [here](https://github.com/Tenpi/crunchyroll.ts/blob/73b4ee5abfc9f39296c3b3bce74e965d3b466f76/entities/Util.ts#L129).

**Eloquent FFmpeg Version:** 0.14.0
**OS:** Windows 10 64-bit

**Comment by federicocarboni** [comment]
I cloned your `crunchyroll.ts` repo and tested the download/conversion with a few different configurations.
After a bit of debugging, I found that setting the log level to `LogLevel.Error` (which was the default in `v0.13.0-alpha.0`) or higher fixes the problem. You can already fix it reliably by either setting the log level to `LogLevel.Quiet` or adding a [`logger`](https://federicocarboni.github.io/eloquent-ffmpeg/api/interfaces/_src_lib_.spawnoptions.html#logger) to the spawn options.
The reason behind this is probably a side effect of my early implementation of logging helpers, and a bad default configuration - this is why the library is still not `1.0`.
