### ISSUE TITLE
SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by gamermao** [FedericoCarboni/eloquent-ffmpeg#18]
Using almost identical code from [here](https://github.com/FedericoCarboni/eloquent-ffmpeg#streams), I get the error in the title. Of course, I replaced the filenames with my own, but no luck.

I also imported both `eloquent-ffmpeg` and `fs` so I really don't know what the issue is considering, from what I can see, there's nothing different.

```
var ffmpeg = require('eloquent-ffmpeg'),
  fs = require('fs');
```

**Comment by federicocarboni** [comment]
The answer is in the error message, commonjs doesn't support top-level `await`s so you have to wrap your code in an `async function`.
```js
async function convertMyVideo() {
  // ...
}
convertMyVideo();
```
```js
// This is fine but note that ffmpeg will be a namespace not a function
var ffmpeg = require('eloquent-ffmpeg');
// If you just want the ffmpeg function
var { ffmpeg } = require('eloquent-ffmpeg');
```

**Comment by gamermao** [comment]
I see, what is commonjs? Does this mean there is a way to avoid needing to wrap it in an async function? I have started learning JS recently so apologies for the basic questions. :]

**Comment by federicocarboni** [comment]
Node.js supports commonjs modules, which use `require` and `exports` and ES6 modules, which use `import` and `export`. You can use es modules instead of commonjs by adding `"type": "module"` to your `package.json` or by changing the file extension from `.js` to `.mjs`. I recommend you read the official guides [Node.js ECMAScript modules](https://nodejs.org/api/esm.html) and [Node.js commonjs modules](https://nodejs.org/api/modules.html).

**Comment by gamermao** [comment]
Thank you, king. And now for my final question.......

i have currently this bit of code:

```
        async function streamVideo() {
            const cmd = ffmpeg();
            cmd.input(fs.createReadStream(stream));
            cmd.output(fs.createWriteStream('./'+Date.now()+'.flv'))
                .format('flv');
            const proc = await cmd.spawn();
            await proc.complete();
            console.log("Stream has finished.");
```

cmd.input(fs.createReadStream(stream)); is supposed to launch [streamlink for nodejs](https://github.com/sanchezand/node-streamlink) and read its buffer output (I had to manually modify it to do this), like so:

```
	let link = message.match(/[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/gi);
        let stream = new Streamlink(link).quality('best').pipe();
```

The modification I made to the streamlink script was adding this pipe()... method? function? I'm still learning -w-:

```
   pipe(done) {
      this.isLive((live)=>{
         if(!live){
            this.emit('err', 'Is not live.');
            return;
         }
         var args = [];
         if(!this.outputLoc){
            args.push('-O');
         }
         args.push(this.stream);
         args.push(this.qual+',worst');
         this.startTime = Math.floor(Date.now()/1000);
   
         this.live = spawn('streamlink', args);
          this.live.stdout.on('data', (d)=>{
             console.log(d);
         });
   
         this.live.on('close', (code, st)=>this.end(code, st));
      })
      return this;
   }
```

Running these though, I get:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Streamlink
```

So it appears to not be recognising it as a buffer. Very weird! :(
